In [ ]:
print("Day-1")

Day-1


In [ ]:
tup=tuple(("ntt",10,20))
print(tup)
ple=iter(tup)
print(next(ple))

('ntt', 10, 20)
ntt


In [ ]:
tupl=tuple(()"ntt"))
print(tupl)

('n', 't', 't')


In [ ]:
tp2=tuple(('15'))
print(tp2)

('1', '5')


In [ ]:
test=tuple([6,8,7,8])
print(test)

print(type(test))

(6, 8, 7, 8)
<class 'tuple'>


In [ ]:
dis={1.2:10,2.2:22}
dis

{1.2: 10, 2.2: 22}

In [ ]:
import numpy as np

a=np.array([[[1,2,3],[2,4,3]],[[1,2,3],[2,4,3]],[[1,2,3],[2,4,3]]])
print(a.ndim)
print(a)
print(a.shape)
print(a.dtype)

3
[[[1 2 3]
  [2 4 3]]

 [[1 2 3]
  [2 4 3]]

 [[1 2 3]
  [2 4 3]]]
(3, 2, 3)
int64


In [ ]:

import numpy as np
arr=np.array([[1,2,3],[2,2,3]])
print(arr)
print(arr.shape)


[[1 2 3]
 [2 2 3]]
(2, 3)
