In [ ]:
print("Day-1")

Day-1


In [ ]:
tup=tuple(("ntt",10,20))
print(tup)
ple=iter(tup)
print(next(ple))

('ntt', 10, 20)
ntt


In [1]:
tupl=tuple(("ntt"))
print(tupl)

('n', 't', 't')


In [ ]:
tp2=tuple(('15'))
print(tp2)

('1', '5')


In [ ]:
test=tuple([6,8,7,8])
print(test)

print(type(test))

(6, 8, 7, 8)
<class 'tuple'>


In [ ]:
dis={1.2:10,2.2:22}
dis

{1.2: 10, 2.2: 22}

In [ ]:
import numpy as np

a=np.array([[[1,2,3],[2,4,3]],[[1,2,3],[2,4,3]],[[1,2,3],[2,4,3]]])
print(a.ndim)
print(a)
print(a.shape)
print(a.dtype)


3
[[[1 2 3]
  [2 4 3]]

 [[1 2 3]
  [2 4 3]]

 [[1 2 3]
  [2 4 3]]]
(3, 2, 3)
int64
<built-in method sort of numpy.ndarray object at 0x7ea8e84557d0>


In [ ]:

import numpy as np
arr=np.array([[1,2,3],[2,2,3]])
print(arr)
print(arr.shape)


[[1 2 3]
 [2 2 3]]
(2, 3)


In [ ]:
dir={"name":"test","server":"test","Ip":"test"}

print(dir)
print(dir["name"])
print(dir.keys())
dir.update({"server":"India"})
print(dir)
print(dir.values())
print(dir.items())
dir["Ip"]="testing"
print(dir["Ip"])

dir.pop("name")

print(dir)


{'name': 'test', 'server': 'test', 'Ip': 'test'}
test
dict_keys(['name', 'server', 'Ip'])
{'name': 'test', 'server': 'India', 'Ip': 'test'}
dict_values(['test', 'India', 'test'])
dict_items([('name', 'test'), ('server', 'India'), ('Ip', 'test')])
testing
{'server': 'India', 'Ip': 'testing'}


In [3]:
dirr=dict(name="india",place="Asia",tes="")
dirr

{'name': 'india', 'place': 'Asia', 'tes': ''}

In [6]:
if "name" in dirr:
  print("yes")
else:
  print("no")

yes


In [18]:
dirr["tes"]="testing"
dirr=dict({"ran":"dom"})

dirr.update({"name":"ind","stt":"ia","di":"and"})
print(dirr)



{'ran': 'dom', 'name': 'ind', 'stt': 'ia', 'di': 'and'}


In [20]:
dirr.pop("stt")
print(dirr)

{'ran': 'dom', 'name': 'ind'}
